# Generated by Django 6.1.1 on 2026-09-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='rental_price',
            new_name='price_per_day',
        ),
        migrations.AddField(
            model_name='bike',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
