# Generated by Django 6.1.1 on 2026-09-17 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rename_rental_price_bike_price_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='planned_return_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
